### ISSUE TITLE
Video does not show end time

### ISSUE THREAD

**Issue by joshuaboniface** [Shadfin/app#19]
Loading a movie on the demo instance (of both Shadfin and the Jellyfin Stable Demo server), there is no end time shown for the video:

![image](https://github.com/user-attachments/assets/fa037b17-5402-44b3-ba9b-087c23c0640f)

**Comment by brys0** [comment]
Oh man, thank you! I haven't even realized you made an issue. Thank you I'll look into this today :)

**Comment by brys0** [comment]
Should be fixed in [8c529bc](https://github.com/Shadfin/app/commit/8c529bc82b7d5e8b672747493e6c92668abd2009) if not please comment!
