### ISSUE TITLE
Login disclaimer doesn't render HTML (like Jellyfin & Jellyfin-Vue do)

### ISSUE THREAD

**Issue by yesBad** [Shadfin/app#30]
https://github.com/user-attachments/assets/9e918f79-ebb5-4bd7-b517-fdb82fdcd9c5

**Comment by brys0** [comment]
Fixed in ee482e0c727f37a3761ea10e064753345707c9cf

Additionally, you can hide elements using the attribute shadfin-hide="true" on any div elements
